import { Tool } from "@/store/useAppStore";

export interface Category {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
}

export const mockCategories: Category[] = [
  { id: "4a45a305-65bb-419b-bb9d-9cf361bc4c80", name: "Writing", slug: "writing", description: "Generate articles, copywriting, blogs, and SEO content.", icon: "writing" },
  { id: "df46b0ab-6571-477d-9494-b15392d47781", name: "Coding", slug: "coding", description: "Intelligent auto-complete, debugging, and agentic workflows.", icon: "coding" },
  { id: "44a04bc6-d446-4cb0-a541-1be0092fa023", name: "Video", slug: "video", description: "AI video editing, synthesis, text-to-video, and avatars.", icon: "video" },
  { id: "c6f5e7c2-9e8c-4a3b-9e45-f0cd12345678", name: "Research", slug: "research", description: "Academic paper search, summaries, and semantic research databases.", icon: "research" },
  { id: "bc2d4e8f-7c6d-4c3e-8c2d-9a8b7c6d5e4f", name: "Marketing", slug: "marketing", description: "Ad graphics generation, social campaigns, and brand assets.", icon: "marketing" },
  { id: "d2a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d6", name: "Design", slug: "design", description: "Text-to-image creation, UI inspiration, and vector graphic assets.", icon: "design" },
  { id: "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d7", name: "Automation", slug: "automation", description: "Connect apps, trigger workflows, and automate tasks with AI nodes.", icon: "automation" },
  { id: "b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e", name: "Productivity", slug: "productivity", description: "AI-powered notes, workspace organizers, and focus planners.", icon: "productivity" },
];

export const mockTools: Tool[] = [
  // WRITING
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d0",
    slug: "chatgpt",
    name: "ChatGPT",
    description: "General purpose conversational agent excellent for writing, coding, and brainstorming.",
    category_id: "4a45a305-65bb-419b-bb9d-9cf361bc4c80",
    category: "Writing",
    website_url: "https://chatgpt.com",
    pricing_model: "freemium",
    best_for_role: ["student", "developer", "designer", "founder", "marketer"],
    difficulty: "beginner",
    pros: ["Highly versatile", "Powerful GPT-4o model", "Custom GPT support"],
    use_cases: ["Content drafting", "Idea brainstorming", "Translation"],
    featured: true,
    popularity_score: 99,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d1",
    slug: "claude",
    name: "Claude",
    description: "AI assistant built with safety in mind, featuring excellent writing formatting and code comprehension.",
    category_id: "4a45a305-65bb-419b-bb9d-9cf361bc4c80",
    category: "Writing",
    website_url: "https://claude.ai",
    pricing_model: "freemium",
    best_for_role: ["student", "developer", "founder"],
    difficulty: "beginner",
    pros: ["Artifacts UI", "Excellent natural prose", "Large 200k context window"],
    use_cases: ["Academic editing", "Technical writing", "Data analysis"],
    featured: true,
    popularity_score: 97,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d2",
    slug: "jasper",
    name: "Jasper AI",
    description: "Enterprise content writing tool specialized in marketing campaigns and blog generation.",
    category_id: "4a45a305-65bb-419b-bb9d-9cf361bc4c80",
    category: "Writing",
    website_url: "https://jasper.ai",
    pricing_model: "paid",
    best_for_role: ["marketer", "founder"],
    difficulty: "intermediate",
    pros: ["Plagiarism checker integration", "Brand voice memory", "Dynamic campaigns templates"],
    use_cases: ["SEO blogging", "Social copywriting", "Marketing materials"],
    featured: false,
    popularity_score: 88,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d3",
    slug: "copyai",
    name: "Copy.ai",
    description: "Automated copywriting assistant for marketing teams, emails, and sales content.",
    category_id: "4a45a305-65bb-419b-bb9d-9cf361bc4c80",
    category: "Writing",
    website_url: "https://copy.ai",
    pricing_model: "freemium",
    best_for_role: ["marketer", "founder"],
    difficulty: "beginner",
    pros: ["Hundreds of copy formulas", "Workflows automations", "Intuitive editor interface"],
    use_cases: ["Ad copy generation", "Email marketing", "Product descriptions"],
    featured: false,
    popularity_score: 86,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d4",
    slug: "grammarly",
    name: "Grammarly AI",
    description: "Real-time grammar, spelling, tone correction, and rewriting suggestions.",
    category_id: "4a45a305-65bb-419b-bb9d-9cf361bc4c80",
    category: "Writing",
    website_url: "https://grammarly.com",
    pricing_model: "freemium",
    best_for_role: ["student", "marketer", "founder"],
    difficulty: "beginner",
    pros: ["Realtime desktop/web integration", "Tone detector", "Plagiarism check"],
    use_cases: ["Spelling correction", "Tone optimization", "Academic styling"],
    featured: false,
    popularity_score: 92,
  },

  // CODING
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d5",
    slug: "cursor",
    name: "Cursor",
    description: "AI-first code editor designed for pair programming, codebase search, and instant editing.",
    category_id: "df46b0ab-6571-477d-9494-b15392d47781",
    category: "Coding",
    website_url: "https://cursor.com",
    pricing_model: "freemium",
    best_for_role: ["developer"],
    difficulty: "intermediate",
    pros: ["Full codebase indexing", "Inline editor suggestions", "Integrated terminal chat"],
    use_cases: ["Codebase searching", "Rapid prototyping", "Error debugging"],
    featured: true,
    popularity_score: 98,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
    slug: "github-copilot",
    name: "GitHub Copilot",
    description: "AI pair programmer extension integrating inline code completions in major IDEs.",
    category_id: "df46b0ab-6571-477d-9494-b15392d47781",
    category: "Coding",
    website_url: "https://github.com/features/copilot",
    pricing_model: "paid",
    best_for_role: ["developer"],
    difficulty: "beginner",
    pros: ["Supports VSCode/Neovim/IntelliJ", "Fast autocomplete", "Code explainers"],
    use_cases: ["Boilerplate creation", "API learning", "Inline suggestions"],
    featured: true,
    popularity_score: 96,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d7",
    slug: "codeium",
    name: "Codeium",
    description: "Free and fast AI-powered autocomplete and chat extension for multiple code editors.",
    category_id: "df46b0ab-6571-477d-9494-b15392d47781",
    category: "Coding",
    website_url: "https://codeium.com",
    pricing_model: "free",
    best_for_role: ["developer", "student"],
    difficulty: "beginner",
    pros: ["Completely free tier", "Support for 70+ languages", "High performance speeds"],
    use_cases: ["Syntax completion", "Unit test writing", "Comments conversion"],
    featured: false,
    popularity_score: 85,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d8",
    slug: "v0",
    name: "v0 by Vercel",
    description: "Generative UI system that builds clean React components, Tailwind styling, and Shadcn formats.",
    category_id: "df46b0ab-6571-477d-9494-b15392d47781",
    category: "Coding",
    website_url: "https://v0.dev",
    pricing_model: "freemium",
    best_for_role: ["developer", "designer"],
    difficulty: "intermediate",
    pros: ["Produces ready React components", "Tailwind pre-styled", "Framer motion support"],
    use_cases: ["UI prototyping", "Component generation", "Frontend styling"],
    featured: true,
    popularity_score: 93,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d9",
    slug: "bolt",
    name: "Bolt.new",
    description: "Full-stack sandbox environment that generates, builds, and deploys Web applications.",
    category_id: "df46b0ab-6571-477d-9494-b15392d47781",
    category: "Coding",
    website_url: "https://bolt.new",
    pricing_model: "freemium",
    best_for_role: ["developer", "founder"],
    difficulty: "advanced",
    pros: ["Complete runtime sandbox", "Installs npm packages", "Instant cloud deployments"],
    use_cases: ["Full-stack generation", "Deploying dashboards", "Web apps prototyping"],
    featured: false,
    popularity_score: 89,
  },

  // VIDEO
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5da",
    slug: "runway",
    name: "Runway Gen-3",
    description: "Cinematic text-to-video and image-to-video generation software with deep visual control.",
    category_id: "44a04bc6-d446-4cb0-a541-1be0092fa023",
    category: "Video",
    website_url: "https://runwayml.com",
    pricing_model: "freemium",
    best_for_role: ["designer", "marketer"],
    difficulty: "intermediate",
    pros: ["Cinematic video quality", "Custom motion brushes", "High frame consistency"],
    use_cases: ["Video concept drafting", "Ad creatives generation", "Motion graphics"],
    featured: true,
    popularity_score: 95,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5db",
    slug: "synthesia",
    name: "Synthesia",
    description: "Create AI avatar video presentations from simple text inputs with support for 120+ languages.",
    category_id: "44a04bc6-d446-4cb0-a541-1be0092fa023",
    category: "Video",
    website_url: "https://synthesia.io",
    pricing_model: "paid",
    best_for_role: ["founder", "marketer"],
    difficulty: "beginner",
    pros: ["150+ realistic avatars", "High-fidelity voices", "No video setup required"],
    use_cases: ["Training videos", "Corporate presentations", "Language localizations"],
    featured: false,
    popularity_score: 90,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5dc",
    slug: "descript",
    name: "Descript",
    description: "AI video and audio editor that lets you edit video by editing text scripts.",
    category_id: "44a04bc6-d446-4cb0-a541-1be0092fa023",
    category: "Video",
    website_url: "https://descript.com",
    pricing_model: "freemium",
    best_for_role: ["student", "marketer", "founder"],
    difficulty: "beginner",
    pros: ["Voice cloning (Overdub)", "Automatic filler word removal", "Audio studio sound cleaner"],
    use_cases: ["Podcast editing", "Captions placement", "Social media video shorts"],
    featured: false,
    popularity_score: 91,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5dd",
    slug: "elevenlabs",
    name: "ElevenLabs",
    description: "Premium AI text-to-speech and voice cloning generator with rich emotional control.",
    category_id: "44a04bc6-d446-4cb0-a541-1be0092fa023",
    category: "Video",
    website_url: "https://elevenlabs.io",
    pricing_model: "freemium",
    best_for_role: ["student", "designer", "marketer", "founder"],
    difficulty: "beginner",
    pros: ["Highly realistic inflections", "Custom voice cloning", "Sound effects generator"],
    use_cases: ["Voiceover generation", "Audiobook narration", "Sound effects designing"],
    featured: true,
    popularity_score: 94,
  },

  // RESEARCH
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5de",
    slug: "perplexity",
    name: "Perplexity",
    description: "Conversational search and answer engine supplying real-time citations and summary context.",
    category_id: "c6f5e7c2-9e8c-4a3b-9e45-f0cd12345678",
    category: "Research",
    website_url: "https://perplexity.ai",
    pricing_model: "freemium",
    best_for_role: ["student", "developer", "founder"],
    difficulty: "beginner",
    pros: ["Full web search indexing", "Precise footnote citations", "Organized collections"],
    use_cases: ["Academic research", "Competitor tracking", "Quick fact-checking"],
    featured: true,
    popularity_score: 97,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5df",
    slug: "elicit",
    name: "Elicit",
    description: "AI research assistant that extracts findings, concepts, and statistics from academic papers.",
    category_id: "c6f5e7c2-9e8c-4a3b-9e45-f0cd12345678",
    category: "Research",
    website_url: "https://elicit.com",
    pricing_model: "freemium",
    best_for_role: ["student"],
    difficulty: "intermediate",
    pros: ["Indexes 200M+ papers", "Auto-summarization grid", "Metadata extraction tables"],
    use_cases: ["Literature review", "Hypothesis testing", "Finding research citations"],
    featured: true,
    popularity_score: 89,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e0",
    slug: "consensus",
    name: "Consensus",
    description: "AI-powered search engine that extracts consensus answers directly from peer-reviewed research.",
    category_id: "c6f5e7c2-9e8c-4a3b-9e45-f0cd12345678",
    category: "Research",
    website_url: "https://consensus.app",
    pricing_model: "freemium",
    best_for_role: ["student"],
    difficulty: "beginner",
    pros: ["Scientific consensus meter", "Auto academic citations", "Plain-English summaries"],
    use_cases: ["Scientific query checks", "Finding research support", "Synthesizing literature"],
    featured: false,
    popularity_score: 87,
  },

  // MARKETING
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e1",
    slug: "adcreative",
    name: "AdCreative.ai",
    description: "Generate conversion-focused advertising banners and social posts using pre-trained visual models.",
    category_id: "bc2d4e8f-7c6d-4c3e-8c2d-9a8b7c6d5e4f",
    category: "Marketing",
    website_url: "https://adcreative.ai",
    pricing_model: "paid",
    best_for_role: ["marketer", "founder"],
    difficulty: "beginner",
    pros: ["Generates 100+ banners quickly", "Ad account integration", "Click-rate predictions"],
    use_cases: ["Facebook/Google ad assets", "Social banner updates", "Ad scoring comparisons"],
    featured: true,
    popularity_score: 92,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e2",
    slug: "predis",
    name: "Predis.ai",
    description: "AI social media tool that turns simple prompts into complete posts, videos, and copies.",
    category_id: "bc2d4e8f-7c6d-4c3e-8c2d-9a8b7c6d5e4f",
    category: "Marketing",
    website_url: "https://predis.ai",
    pricing_model: "freemium",
    best_for_role: ["marketer", "founder"],
    difficulty: "beginner",
    pros: ["Generates posts and reels", "Competitor analysis", "Post scheduler"],
    use_cases: ["Instagram scheduling", "TikTok reels generation", "Brand posting automations"],
    featured: false,
    popularity_score: 83,
  },

  // DESIGN
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e3",
    slug: "midjourney",
    name: "Midjourney",
    description: "State-of-the-art text-to-image generator known for premium textures and details.",
    category_id: "d2a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
    category: "Design",
    website_url: "https://midjourney.com",
    pricing_model: "paid",
    best_for_role: ["designer", "marketer"],
    difficulty: "intermediate",
    pros: ["High aesthetic quality", "Vibrant colors", "Deep style controls"],
    use_cases: ["Concept art designing", "UI layouts mockups", "Digital assets creation"],
    featured: true,
    popularity_score: 98,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e4",
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    description: "Commercially safe generative AI models integrated into Photoshop, Illustrator, and Premiere.",
    category_id: "d2a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
    category: "Design",
    website_url: "https://adobe.com/firefly",
    pricing_model: "freemium",
    best_for_role: ["designer", "marketer"],
    difficulty: "intermediate",
    pros: ["Commercial safety guarantee", "Adobe app suite integrations", "Vector recolor support"],
    use_cases: ["Generative fills", "Vector graphics design", "Ad background creation"],
    featured: false,
    popularity_score: 90,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e5",
    slug: "canva-ai",
    name: "Canva AI",
    description: "Suite of AI graphic design elements including Magic Studio, background removal, and layouts.",
    category_id: "d2a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
    category: "Design",
    website_url: "https://canva.com",
    pricing_model: "freemium",
    best_for_role: ["student", "marketer", "designer", "founder"],
    difficulty: "beginner",
    pros: ["Super simple drag-drop UI", "Huge assets database", "Team design sharing"],
    use_cases: ["Social assets creation", "Deck slides styling", "Ad asset editing"],
    featured: false,
    popularity_score: 91,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e6",
    slug: "galileo-ai",
    name: "Galileo AI",
    description: "Text-to-UI designer that creates fully editable Figma UI screens and code tokens.",
    category_id: "d2a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
    category: "Design",
    website_url: "https://usegalileo.ai",
    pricing_model: "freemium",
    best_for_role: ["designer", "developer", "founder"],
    difficulty: "intermediate",
    pros: ["Exports directly to Figma", "React/Tailwind export support", "Clean layout structures"],
    use_cases: ["Mobile screen mockups", "Landing page prototyping", "Figma wireframing"],
    featured: true,
    popularity_score: 89,
  },

  // AUTOMATION
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e7",
    slug: "zapier",
    name: "Zapier",
    description: "Integrate 6000+ apps and construct workflows with multi-step triggers and AI paths.",
    category_id: "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d7",
    category: "Automation",
    website_url: "https://zapier.com",
    pricing_model: "freemium",
    best_for_role: ["founder", "developer", "marketer"],
    difficulty: "beginner",
    pros: ["Huge app integration library", "Easy visual builder", "Zapier Copilot AI assistant"],
    use_cases: ["Leads database sync", "Automatic alerts sending", "Cross-app actions"],
    featured: true,
    popularity_score: 96,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e8",
    slug: "make",
    name: "Make",
    description: "Visual logic builder for designing complex and cost-effective automations with data maps.",
    category_id: "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d7",
    category: "Automation",
    website_url: "https://make.com",
    pricing_model: "freemium",
    best_for_role: ["founder", "developer"],
    difficulty: "intermediate",
    pros: ["Highly visual diagrams", "Cost-effective loops", "Deep data manipulation"],
    use_cases: ["Complex business syncing", "Webhook handlers routing", "Multi-stage API loops"],
    featured: false,
    popularity_score: 90,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5e9",
    slug: "n8n",
    name: "n8n",
    description: "Fair-code node automations editor with support for self-hosting and AI agent components.",
    category_id: "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d7",
    category: "Automation",
    website_url: "https://n8n.io",
    pricing_model: "freemium",
    best_for_role: ["developer", "founder"],
    difficulty: "advanced",
    pros: ["Self-host support", "AI node components built-in", "Node Javascript scripting"],
    use_cases: ["AI agent workflows", "Data privacy automations", "Scheduled server operations"],
    featured: true,
    popularity_score: 87,
  },

  // PRODUCTIVITY
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5ea",
    slug: "notion-ai",
    name: "Notion AI",
    description: "AI-integrated wiki workspace database for formatting notes, tables, and pages.",
    category_id: "b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e",
    category: "Productivity",
    website_url: "https://notion.so",
    pricing_model: "freemium",
    best_for_role: ["student", "developer", "designer", "founder", "marketer"],
    difficulty: "beginner",
    pros: ["Organized database tables", "Auto-summary columns", "Inline text assistant"],
    use_cases: ["Knowledge bases", "Meeting minutes summaries", "Task planning boards"],
    featured: true,
    popularity_score: 95,
  },
  {
    id: "52a1c3b4-e5f6-7a8b-9c0d-e1f2a3b4c5eb",
    slug: "motion",
    name: "Motion",
    description: "AI calendar coordinator that schedules meetings, tasks, and items automatically.",
    category_id: "b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e",
    category: "Productivity",
    website_url: "https://usemotion.com",
    pricing_model: "paid",
    best_for_role: ["founder", "developer", "marketer"],
    difficulty: "beginner",
    pros: ["Automated calendar blocks", "Unified team schedule", "Priority tracker"],
    use_cases: ["Task schedule blocks", "Meeting request slots", "Priority management"],
    featured: true,
    popularity_score: 91,
  },
];
